/**
 * Generate the capability matrix (backend x the 7 capability flags) FROM each
 * adapter's declared `Capabilities`, so the published matrix can't drift from the
 * code. Reads `backend.capabilities` off a dummy-config construction of each
 * adapter (no network: clients connect lazily), iterates `CAPABILITY_KEYS` from
 * core, and writes `docs/CAPABILITIES.md`.
 *
 *   node scripts/capability-matrix.mjs          # regenerate docs/CAPABILITIES.md
 *   node scripts/capability-matrix.mjs --check   # fail if the committed file is stale
 *
 * Imports the BUILT dists by relative path (the repo root doesn't depend on the
 * workspace packages, so bare `@baas/*` specifiers wouldn't resolve here); run
 * `turbo run build` first. The `--check` mode runs in CI.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createConvexBackend } from "../packages/adapter-convex/dist/index.js";
import { createMemoryBackend } from "../packages/adapter-memory/dist/index.js";
import { createSupabaseBackend } from "../packages/adapter-supabase/dist/index.js";
import { CAPABILITY_KEYS } from "../packages/core/dist/index.js";

// One-line description per capability (stable, human-authored): what a `true`
// flag MEANS for a caller. The booleans come from the adapters; this is the prose.
const DESCRIPTIONS = {
  multiDocumentTransactions:
    "A `mutate` commits all its writes together or none (atomic rollback).",
  reactiveQueries: "`subscribe` delivers LIVE updates, not just an initial value.",
  serverSideJoins: "Server-side joins / nested selects are available (via `native()`).",
  aggregations: "Aggregations / group-by are available (via `native()`).",
  efficientFilterRequiresIndex:
    "Filtering an unindexed field is a full scan, not an efficient lookup.",
  managesCredentials: "The auth provider runs sign-in flows, not just JWT verification.",
  fileStorage: "A `FileStore` is available.",
};

// Dummy configs: capabilities are static constants, so no real backend is needed.
const empty = { queries: {}, mutations: {} };
const ADAPTERS = [
  ["memory", createMemoryBackend(empty)],
  ["supabase", createSupabaseBackend({ ...empty, url: "http://localhost", key: "dummy" })],
  ["convex", createConvexBackend({ ...empty, url: "http://localhost" })],
];

const tick = (b) => (b ? "✅" : "❌");

function render() {
  const names = ADAPTERS.map(([n]) => n);
  const header = `| Capability | ${names.join(" | ")} | What \`true\` means |`;
  const sep = `|---|${names.map(() => ":-:").join("|")}|---|`;
  const rows = CAPABILITY_KEYS.map((key) => {
    const cells = ADAPTERS.map(([, backend]) => tick(backend.capabilities[key]));
    return `| \`${key}\` | ${cells.join(" | ")} | ${DESCRIPTIONS[key] ?? ""} |`;
  });
  return [
    "<!-- GENERATED by scripts/capability-matrix.mjs from each adapter's declared",
    "     Capabilities. Do not edit by hand; run `pnpm docs:capabilities`. -->",
    "",
    "# Capability matrix",
    "",
    "Every divergence between backends is a declared capability flag, asserted in",
    "both directions by the conformance suite. This table is generated from each",
    "adapter's `Capabilities`, so it cannot drift from the code.",
    "",
    header,
    sep,
    ...rows,
    "",
    "## Notes",
    "",
    "- The table reflects each backend's **default** capabilities. Supabase",
    "  `reactiveQueries` is opt-in: declaring a `realtime` watch on a query flips it",
    "  to `true`, and `subscribe` then delivers live updates by re-running the query",
    "  on watched-table changes. See the adapter README.",
    "",
  ].join("\n");
}

const OUT = fileURLToPath(new URL("../docs/CAPABILITIES.md", import.meta.url));
const generated = render();

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing file => mismatch */
  }
  if (current !== generated) {
    console.error("docs/CAPABILITIES.md is stale. Run `pnpm docs:capabilities` and commit.");
    process.exit(1);
  }
  console.log("capability matrix is in sync.");
} else {
  writeFileSync(OUT, generated);
  console.log(`wrote ${OUT}`);
}

// A constructed ConvexClient holds an open socket that keeps the event loop
// alive; the work is synchronous and done, so exit explicitly.
process.exit(0);
